version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
build:
  project: WickedEngine.sln
  parallel: true
  verbosity: minimal
platform:
  - x64
  - Win32
install:
  - cmd: c:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Community\Common7\IDE\devenv.exe "WickedEngine/WickedEngine_SHARED.vcxitems" /upgrade
  - dir
after_build:
  - cmd: move %APPVEYOR_BUILD_FOLDER%\%PLATFORM%\Release\Editor.exe %APPVEYOR_BUILD_FOLDER%\Editor
  - cmd: 7z a WickedEngineEditor.zip WickedEngine\shaders\ WickedEngine\fonts\ images\ models\ scripts\ shadercompilers\ Documentation\ *.txt *.md Editor\Editor.exe Editor\images\ Editor\sound\ Editor\*.ini Editor\*.ico Editor\*.lua
  - cmd: move %APPVEYOR_BUILD_FOLDER%\%PLATFORM%\Release\Tests.exe %APPVEYOR_BUILD_FOLDER%\Tests
  - cmd: 7z a WickedEngineTests.zip WickedEngine\shaders\ WickedEngine\fonts\ images\ models\ scripts\ shadercompilers\ Documentation\ *.txt *.md Tests\Tests.exe Tests\images\ Tests\sound\ Tests\*.ini Tests\*.ico Tests\*.lua Tests\*.ttf
  
artifacts:
- path: WickedEngineEditor.zip
  name: Editor
- path: WickedEngineTests.zip
  name: Tests

